# Generated by Django 6.0.1 on 2026-01-18 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(db_column='id_pedido', primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField()),
                ('total_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.RESTRICT, related_name='pedidos', to='core.cliente')),
                ('estado_pedido', models.ForeignKey(db_column='id_estado_pedido', default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='pedidos', to='core.estadopedido')),
            ],
            options={
                'db_table': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id_linea_pedido', models.AutoField(db_column='id_linea_pedido', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_iva', models.DecimalField(decimal_places=2, max_digits=4)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.RESTRICT, related_name='lineas_pedido', to='core.producto')),
                ('pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='ventas.pedido')),
            ],
            options={
                'db_table': 'LineaPedido',
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente', 'fecha_pedido'], name='idx_pedido_cliente_fecha'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente'], name='idx_pedido_cliente_top'),
        ),
    ]
