# Generated by Django 5.2.8 on 2026-04-13 11:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(db_column='id_pedido', primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.RESTRICT, related_name='pedidos', to='core.cliente')),
                ('estado_pedido', models.ForeignKey(db_column='id_estado_pedido', default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='pedidos', to='core.estadopedido')),
            ],
            options={
                'db_table': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id_linea_pedido', models.AutoField(db_column='id_linea_pedido', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_iva', models.DecimalField(decimal_places=2, max_digits=4)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.RESTRICT, related_name='lineas_pedido', to='core.producto')),
                ('pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='ventas.pedido')),
            ],
            options={
                'db_table': 'LineaPedido',
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='check_cantidad_positiva')],
            },
        ),
    ]
